# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/root07/Desktop/Final year/EEE4120F/Assignments/Ass5/Vivado IP and Resource Usage/FullSine/FullSine.srcs/sources_1/ip/blk_mem_gen/blk_mem_gen.xci
# IP: The module: 'blk_mem_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/root07/Desktop/Final year/EEE4120F/Assignments/Ass5/Vivado IP and Resource Usage/FullSine/FullSine.srcs/sources_1/ip/blk_mem_gen/blk_mem_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/root07/Desktop/Final year/EEE4120F/Assignments/Ass5/Vivado IP and Resource Usage/FullSine/FullSine.srcs/sources_1/ip/blk_mem_gen/blk_mem_gen.xci
# IP: The module: 'blk_mem_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/root07/Desktop/Final year/EEE4120F/Assignments/Ass5/Vivado IP and Resource Usage/FullSine/FullSine.srcs/sources_1/ip/blk_mem_gen/blk_mem_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
